//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meeting_users()
        {
            this.questions = new HashSet<question>();
            this.shrh_vote = new HashSet<shrh_vote>();
        }
    
        public string shr_meet_kind { get; set; }
        public string shr_meet_date { get; set; }
        public decimal comp_id { get; set; }
        public string shrh_code { get; set; }
        public string presence_type { get; set; }
        public System.DateTime update_date { get; set; }
        public string status { get; set; }
    
        public virtual shareholder shareholder { get; set; }
        public virtual shr_meeting shr_meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shrh_vote> shrh_vote { get; set; }
    }
}
