//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHAREHOLDER_REL
    {
        public string SHRH_CODE { get; set; }
        public string SHA_SHRH_CODE { get; set; }
        public string USER_ID { get; set; }
        public string SHR_REL_KIND { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string INLAW { get; set; }
        public string MEETING_FLAG { get; set; }
        public string NOTE { get; set; }
        public string TBL_DATE { get; set; }
        public string EFF_DATE { get; set; }
    }
}
