//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class shr_meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shr_meeting()
        {
            this.shrh_vote_sub = new HashSet<shrh_vote_sub>();
            this.questions = new HashSet<question>();
            this.shrh_vote = new HashSet<shrh_vote>();
            this.meeting_users = new HashSet<meeting_users>();
            this.meeting_print = new HashSet<meeting_print>();
        }
    
        public string shr_meet_kind { get; set; }
        public string shr_meet_date { get; set; }
        public decimal comp_id { get; set; }
        public string meet_add { get; set; }
        public string meet_time { get; set; }
        public System.DateTime update_date { get; set; }
        public string user_id { get; set; }
        public string form_name { get; set; }
    
        public virtual management_user management_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shrh_vote_sub> shrh_vote_sub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shrh_vote> shrh_vote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_users> meeting_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_print> meeting_print { get; set; }
    }
}
