//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class shrh_vote_sub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shrh_vote_sub()
        {
            this.svot_item = new HashSet<svot_item>();
        }
    
        public decimal svot_no { get; set; }
        public string user_id { get; set; }
        public string shr_meet_kind { get; set; }
        public string shr_meet_date { get; set; }
        public string desc1 { get; set; }
        public string svot_kind { get; set; }
        public string vote_need { get; set; }
        public Nullable<decimal> max_item { get; set; }
        public decimal comp_id { get; set; }
        public string voting_start_flag { get; set; }
    
        public virtual management_user management_user { get; set; }
        public virtual shr_meeting shr_meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<svot_item> svot_item { get; set; }
    }
}
