//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class svot_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public svot_item()
        {
            this.shrh_vote = new HashSet<shrh_vote>();
        }
    
        public decimal svot_no { get; set; }
        public decimal svot_item_no { get; set; }
        public string user_id { get; set; }
        public string desc1 { get; set; }
        public System.DateTime update_date { get; set; }
        public decimal comp_id { get; set; }
        public string picture { get; set; }
    
        public virtual management_user management_user { get; set; }
        public virtual shrh_vote_sub shrh_vote_sub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shrh_vote> shrh_vote { get; set; }
        public virtual company company { get; set; }
    }
}
