//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_fb_shareholder
    {
        public string shrh_code { get; set; }
        public string seplc_code { get; set; }
        public string natid { get; set; }
        public string tax_level { get; set; }
        public string bank_code { get; set; }
        public string bank_branch_code { get; set; }
        public string user_id { get; set; }
        public string sp_shrh_code { get; set; }
        public string cityid { get; set; }
        public string address { get; set; }
        public string tel_no_1 { get; set; }
        public string cell_phone { get; set; }
        public string fax_no { get; set; }
        public string zip_code { get; set; }
        public string tel_no_2 { get; set; }
        public string e_mail { get; set; }
        public string post_box { get; set; }
        public string cert_no { get; set; }
        public string surname1 { get; set; }
        public string name1 { get; set; }
        public string father1 { get; set; }
        public string d1_issu_cert { get; set; }
        public string cert_city { get; set; }
        public string d1_birth { get; set; }
        public string birth_city { get; set; }
        public string serial_cert_no { get; set; }
        public string nat_code { get; set; }
        public string buss_kind { get; set; }
        public string inst_kind { get; set; }
        public string eco_code { get; set; }
        public string tbl_date { get; set; }
        public string shrh_kind { get; set; }
        public string shrh_activity { get; set; }
        public string shrh_exch_code { get; set; }
        public string shrh_first_serial { get; set; }
        public string note { get; set; }
        public string shrh_acc { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string shrh_bbs_code { get; set; }
        public string shrh_pwd { get; set; }
        public string acc_kind_code { get; set; }
        public string sp_class_code { get; set; }
        public string sp_class_item_code { get; set; }
        public string sex { get; set; }
        public string sp_bank_code { get; set; }
        public string bank_acc_name { get; set; }
        public string d1_bank { get; set; }
        public string pkey_shrh_code { get; set; }
    }
}
